version: "3.8"

services:
  docker-control:
    container_name: docker-control
    image: simple-docker-control
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
